name: Data pipline

on:
  workflow_dispatch:

    # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '30 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn index.js
